CREATE TABLE 09_PRODUCT(
	ID int UNSIGNED AUTO_INCREMENT,
	NAME varchar(100),
    PRICE FLOAT(71,2),
    CREATED_AT DATETIME,
    CREATED_BY varchar(100),
	primary key(id)
);
 
 CREATE TABLE `09_CUSTOMER` (
  `ID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `CPF_CNPJ` varchar(14) NOT NULL,
  `STATUS` char(1) NOT NULL DEFAULT '1' COMMENT '1-ATIVO\\n0- INATIVO',
  `CREATED_AT` datetime DEFAULT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `FONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_CUSTOMER_01` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

 
CREATE TABLE 09_SALES_ORDER(
	ID_SALE INT UNSIGNED AUTO_INCREMENT,
    NAME VARCHAR(200),
    ID_CUSTOMER int UNSIGNED,
    ID_PRODUCT INT UNSIGNED,
    QUANTITY INT UNSIGNED,
    ITEM_PRICE FLOAT(10,2),
    NET_PRICE FLOAT(10,2),
	CREATED_AT DATETIME,
    CREATED_BY varchar(100),
    primary key (ID_SALE)
 );
 
 
/*
Alterar as tabelas criadas, XX_PRODUCT, XX_SALES_ORDER para inserir as colunas 
UPDATED_AT e UPDATED_BY).
*/
ALTER TABLE 09_PRODUCT
ADD COLUMN UPDATED_AT DATETIME AFTER CREATED_BY,
ADD COLUMN UPDATED_BY VARCHAR(100);

ALTER TABLE 09_SALES_ORDER
ADD COLUMN UPDATED_AT DATETIME AFTER CREATED_BY,
ADD COLUMN UPDATED_BY VARCHAR(100);

/*
Criar Foreing Key na tabela XX_SALES_ORDER, nas colunas (ID_CUSTOMER, ID_PRODUCT)
*/

ALTER TABLE 09_SALES_ORDER 
ADD CONSTRAINT  fk_sale 
FOREIGN KEY (ID_PRODUCT) REFERENCES 09_PRODUCT(ID);

ALTER TABLE 09_SALES_ORDER
ADD CONSTRAINT fk_CUSTOMER
FOREIGN KEY (ID_CUSTOMER) REFERENCES 09_CUSTOMER(ID);

