INSERT INTO `estagio2019`.`09_PRODUCT`
(`ID`,`nome`,`PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`)
VALUES
(NULL,'arroz',10.5,NOW(),'joao',NULL,NULL);


INSERT INTO `estagio2019`.`09_PRODUCT`
(`ID`,`nome`,`PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`)
VALUES
(NULL,'feijao',8.5,NOW(),'paulo',NULL,NULL);

INSERT INTO `estagio2019`.`09_PRODUCT`
(`ID`,`nome`,`PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`)
VALUES
(NULL,'bife',1.5,NOW(),'oliveira',NULL,NULL);

INSERT INTO `estagio2019`.`09_PRODUCT`
(`ID`,`nome`,`PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`)
VALUES
(NULL,'batata',5.5,NOW(),'joao',NULL,NULL);

INSERT INTO `estagio2019`.`09_PRODUCT`
(`ID`,`nome`,`PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`)
VALUES
(NULL,'salada',6.5,NOW(),'joao',NULL,NULL);



INSERT INTO `estagio2019`.`09_CUSTOMER`
(`ID`,`NAME`,`CPF_CNPJ`,`STATUS`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`,`FONE`)
VALUES
(NULL, 'joao',11122211112,'1',NOW(),'joao',NULL,NULL,'34111111111');

INSERT INTO `estagio2019`.`09_CUSTOMER`
(`ID`,`NAME`,`CPF_CNPJ`,`STATUS`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`,`FONE`)
VALUES
(NULL, 'paulo',11122211112,'1',NOW(),'joao',NULL,NULL,'34111111111');


INSERT INTO `estagio2019`.`09_CUSTOMER`
(`ID`,`NAME`,`CPF_CNPJ`,`STATUS`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`,`UPDATED_BY`,`FONE`)
VALUES
(NULL, 'oliveira',11122211112,'1',NOW(),'joao',NULL,NULL,'34111111111');



INSERT INTO `estagio2019`.`09_SALES_ORDER`
(`ID_SALE`,`NAME`,`ID_CUSTOMER`,`ID_PRODUCT`,`QUANTITY`,`ITEM_PRICE`,`NET_PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`, `UPDATED_BY`)
VALUES
(NULL,'joao',12,
7,5, (SELECT PRICE FROM 09_PRODUCT WHERE ID = 7),
QUANTITY * ITEM_PRICE,
NOW(),'joao',NULL,NULL);

INSERT INTO `estagio2019`.`09_SALES_ORDER`
(`ID_SALE`,`NAME`,`ID_CUSTOMER`,`ID_PRODUCT`,`QUANTITY`,`ITEM_PRICE`,`NET_PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`, `UPDATED_BY`)
VALUES
(NULL,'joao',12,
7,5, (SELECT PRICE FROM 09_PRODUCT WHERE ID = 7),
QUANTITY * ITEM_PRICE,
NOW(),'joao',NULL,NULL);

INSERT INTO `estagio2019`.`09_SALES_ORDER`
(`ID_SALE`,`NAME`,`ID_CUSTOMER`,`ID_PRODUCT`,`QUANTITY`,`ITEM_PRICE`,`NET_PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`, `UPDATED_BY`)
VALUES
(NULL,'PAULO',13,
8,5, 5*(SELECT PRICE FROM 09_PRODUCT WHERE ID = 8),
QUANTITY * ITEM_PRICE,
NOW(),'joao',NULL,NULL);

INSERT INTO `estagio2019`.`09_SALES_ORDER`
(`ID_SALE`,`NAME`,`ID_CUSTOMER`,`ID_PRODUCT`,`QUANTITY`,`ITEM_PRICE`,`NET_PRICE`,`CREATED_AT`,`CREATED_BY`,`UPDATED_AT`, `UPDATED_BY`)
VALUES
(NULL,'joao',12,
9,5, (SELECT PRICE FROM 09_PRODUCT WHERE ID = 9),
QUANTITY * ITEM_PRICE,
NOW(),'joao',NULL,NULL);



SELECT nome, CPF_CNPJ, QUANTITY,ITEM_PRICE, ITEM_PRICE
FROM 09_CUSTOMER c
INNER JOIN 09_SALES_ORDER s on s.ID_CUSTOMER = c.ID
INNER JOIN 09_PRODUCT p on s.ID_PRODUCT = p.ID;
/*
CUSTOMER
12 - JOAO
13 - PAULO
14 - OLIVEIRA

PRODUCT
7 - arroz
8 - feijao
9 - bife
10 - batata
11 - salada
*/